### ISSUE TITLE
Getting strange schema change after migration

### ISSUE THREAD

**Issue by djShrek** [homanchou/the_drawing_challenge#19]
When I clone the git repo, I check the schema and the part that creates the participation table looks like this:

```ruby
  create_table "participations", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "challenge_id"
    t.text     "title"
    t.text     "description"
    t.text     "image_url"
    t.datetime "submitted_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "wins",         default: 0
    t.integer  "losses",       default: 0
    t.float    "rank",         default: 0.0
  end
```

However, after I run the migration (rake db:migrate), the schema changes to this:

```ruby 
  create_table "participations", force: :cascade do |t|
    t.integer  "user_id"
    t.integer  "challenge_id"
    t.datetime "joined_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end
```

So now the wins, losses, rank, title, description, image_url, submitted_at properties are now missing, which is breaking some of the views.  The most recent migration file is just creating the vote model and does not alter anything in the participation model, so I don't see what can be changing the participation model after running all the migrations. Any ideas on what you think can be causing the problem? 

Thanks,

-Robert

**Comment by djShrek** [comment]
Hm, when I remove this line: 

```ruby
add_index :participations, [:user_id, :challenge_id], unique: true
```

from the migration file, everything works fine. I'll comment it out for now and research why this is happening.

**Comment by homanchou** [comment]
Hmm... that's very odd.

That doesn't happen for me:

homanchou:~/Sites/the_drawing_challenge (master) $ rake db:drop

homanchou:~/Sites/the_drawing_challenge (master) $ rake db:create

homanchou:~/Sites/the_drawing_challenge (master) $ rake db:migrate

== 20140928214630 DeviseCreateUsers: migrating
================================

-- create_table(:users)

   -> 0.0456s

-- add_index(:users, :email, {:unique=>true})

   -> 0.0031s

-- add_index(:users, :reset_password_token, {:unique=>true})

   -> 0.0025s

== 20140928214630 DeviseCreateUsers: migrated (0.0515s)
=======================


== 20140928221718 AddColumnsToUsers: migrating
================================

-- add_column(:users, :provider, :string)

   -> 0.0013s

-- add_column(:users, :uid, :string)

   -> 0.0006s

== 20140928221718 AddColumnsToUsers: migrated (0.0022s)
=======================


== 20140928223243 AddMoreColumnsToUsers: migrating
============================

-- add_column(:users, :oauth, :json)

   -> 0.0012s

-- add_column(:users, :avatar, :text)

   -> 0.0007s

== 20140928223243 AddMoreColumnsToUsers: migrated (0.0022s)
===================


== 20140928230143 AddNameToUsers: migrating
===================================

-- add_column(:users, :name, :string)

   -> 0.0010s

== 20140928230143 AddNameToUsers: migrated (0.0010s)
==========================


== 20141026213353 AddRoleColumnToUsers: migrating
=============================

-- add_column(:users, :role, :string)

   -> 0.0009s

== 20141026213353 AddRoleColumnToUsers: migrated (0.0010s)
====================


== 20141123223938 CreateChallenges: migrating
=================================

-- create_table(:challenges)

   -> 0.0211s

== 20141123223938 CreateChallenges: migrated (0.0212s)
========================


== 20141123224354 CreateParticipations: migrating
=============================

-- create_table(:participations)

   -> 0.0051s

-- add_index(:participations, [:user_id, :challenge_id], {:unique=>true})

   -> 0.0020s

== 20141123224354 CreateParticipations: migrated (0.0072s)
====================


== 20150111041208 CreateVotes: migrating
======================================

-- create_table(:votes)

   -> 0.0030s

== 20150111041208 CreateVotes: migrated (0.0030s)
=============================


homanchou:~/Sites/the_drawing_challenge (master) $

Here is the schema


# encoding: UTF-8

# This file is auto-generated from the current state of the database.
Instead

# of editing this file, please use the migrations feature of Active Record
to

# incrementally modify your database, and then regenerate this schema
definition.

#

# Note that this schema.rb definition is the authoritative source for your

# database schema. If you need to create the application database on another

# system, you should be using db:schema:load, not running all the migrations

# from scratch. The latter is a flawed and unsustainable approach (the more
migrations

# you'll amass, the slower it'll run and the greater likelihood for issues).

#

# It's strongly recommended that you check this file into your version
control system.


ActiveRecord::Schema.define(version: 20150111041208) do


  # These are extensions that must be enabled in order to support this
database

  enable_extension "plpgsql"


  create_table "challenges", force: :cascade do |t|

    t.text     "title"

    t.datetime "start_at"

    t.datetime "end_at"

    t.text     "description"

    t.datetime "created_at"

    t.datetime "updated_at"

  end


  create_table "participations", force: :cascade do |t|

    t.integer  "user_id"

    t.integer  "challenge_id"

    t.text     "title"

    t.text     "description"

    t.text     "image_url"

    t.datetime "submitted_at"

    t.datetime "created_at"

    t.datetime "updated_at"

    t.integer  "wins",         default: 0

    t.integer  "losses",       default: 0

    t.float    "rank",         default: 0.0

  end


  add_index "participations", ["user_id", "challenge_id"], name:
"index_participations_on_user_id_and_challenge_id", unique: true, using:
:btree


  create_table "users", force: :cascade do |t|

    t.string   "email",                  default: "", null: false

    t.string   "encrypted_password",     default: "", null: false

    t.string   "reset_password_token"

    t.datetime "reset_password_sent_at"

    t.datetime "remember_created_at"

    t.integer  "sign_in_count",          default: 0,  null: false

    t.datetime "current_sign_in_at"

    t.datetime "last_sign_in_at"

    t.inet     "current_sign_in_ip"

    t.inet     "last_sign_in_ip"

    t.datetime "created_at"

    t.datetime "updated_at"

    t.string   "provider"

    t.string   "uid"

    t.json     "oauth"

    t.text     "avatar"

    t.string   "name"

    t.string   "role"

  end


  add_index "users", ["email"], name: "index_users_on_email", unique: true,
using: :btree

  add_index "users", ["reset_password_token"], name:
"index_users_on_reset_password_token", unique: true, using: :btree


  create_table "votes", force: :cascade do |t|

    t.integer  "user_id"

    t.integer  "challenge_id"

    t.text     "voting_history", default: [],              array: true

    t.datetime "created_at",                  null: false

    t.datetime "updated_at",                  null: false

  end


end

**Comment by homanchou** [comment]
could not duplicate
